#!/usr/bin/python

level1 = [
"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW",
"W                  WWWWWWWWWWWW",
"W         WWWWWW   WWWWWWWWWWWW",
"W   WWWW       W   WWWWWWWWWWWW",
"W   W        WWWW  WWWWWWWWWWWW",
"W WWW  WWWW        WWWWWWWWWWWW",
"W   W     W W      WWWWWWWWWWWW",
"W   W     W   WWW             W",
"W   WWW WWW   W W  WWWWWWWWWWWW",
"W     W   W   W W  WWWWWWWWWWWW",
"WWW   W   WWWWW W  WWWWWWWWWWWW",
"W W      WW        WWWWWWWWWWWW",
"W W   WWWW   WWW   WWWWWWWWWWWW",
"W     W    E   W   WWWWWWWWWWWW",
"WWWWWWWWWWWWW WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWW WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWW WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWW WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWW WWWWWWWWWWWWWWWWW",
"WWWWWWWWWWWWW WWWWWWWWWWWWWWWWW",
]
